In [1]:
import pandas as pd

In [2]:
rdrive = '/mnt/researchdrive/BOX_INTERNAL/opotowsky/'

lbls = ['ReactorType', 'CoolingTime', 'Enrichment', 'Burnup', 'OrigenReactor']
nonlbls = ['AvgPowerDensity', 'ModDensity', 'UiWeight']
nuc_list = ['ac227', 'am241', 'am243', 'ba133', 'cf249', 'cf252', 'cm243', 'cm244', 
            'cm245', 'cs134', 'cs137', 'eu152', 'eu154', 'ho166m', 'kr85', 'nb94', 
            'np236', 'np237', 'pa231', 'pm146', 'pu236', 'pu238', 'pu239', 'pu240', 
            'ra226', 'sb125', 'th228', 'th229', 'u232', 'u233', 'u234', 'u235']

In [3]:
db = pd.read_pickle(rdrive + 'nuc32_activities_scaled_1g_reindex.pkl')

In [4]:
# Source age needs to be above but close to zero because these activities are pre-decayed.
# study is in a directory in gadras detector response repo
# the below time is 20 min
db['Age'] = 3.805175e-5 
db.head()

,ReactorType,CoolingTime,Enrichment,Burnup,OrigenReactor,AvgPowerDensity,ModDensity,UiWeight,ac227,am241,...,pu240,ra226,sb125,th228,th229,u232,u233,u234,u235,Age
0,bwr,117.108292,0.55,1051.45,ge7x7-0,10.0,0.1,1,5.928000e-15,0.000001,...,0.000027,1.554000e-15,0.000389,1.696000e-12,3.467000e-16,1.423000e-11,3.107000e-12,0.000002,1.013000e-08,0.000038
1,bwr,237.640559,0.55,1051.45,ge7x7-0,10.0,0.1,1,1.122000e-14,0.000003,...,0.000027,3.693000e-15,0.000358,3.252000e-12,4.437000e-16,1.668000e-11,3.115000e-12,0.000002,1.013000e-08,0.000038
2,bwr,294.185773,0.55,1051.45,ge7x7-0,10.0,0.1,1,1.393000e-14,0.000003,...,0.000027,5.011000e-15,0.000344,4.015000e-12,4.892000e-16,1.776000e-11,3.119000e-12,0.000002,1.013000e-08,0.000038
3,bwr,362.419607,0.55,1051.45,ge7x7-0,10.0,0.1,1,1.741000e-14,0.000004,...,0.000027,6.869000e-15,0.000328,4.957000e-12,5.443000e-16,1.901000e-11,3.124000e-12,0.000002,1.013000e-08,0.000038
4,bwr,509.653584,0.55,1051.45,ge7x7-0,10.0,0.1,1,2.565000e-14,0.000005,...,0.000027,1.187000e-14,0.000297,7.044000e-12,6.634000e-16,2.150000e-11,3.134000e-12,0.000002,1.013000e-08,0.000038

In [5]:
db = db[['Age'] + nuc_list]
db.head()

,Age,ac227,am241,am243,ba133,cf249,cf252,cm243,cm244,cm245,...,pu239,pu240,ra226,sb125,th228,th229,u232,u233,u234,u235
0,0.000038,5.928000e-15,0.000001,2.261000e-09,7.064000e-13,5.082000e-23,1.003000e-23,4.656000e-10,2.152000e-08,2.244000e-13,...,0.000086,0.000027,1.554000e-15,0.000389,1.696000e-12,3.467000e-16,1.423000e-11,3.107000e-12,0.000002,1.013000e-08
1,0.000038,1.122000e-14,0.000003,2.261000e-09,6.912000e-13,8.814000e-23,9.198000e-24,4.620000e-10,2.125000e-08,2.244000e-13,...,0.000086,0.000027,3.693000e-15,0.000358,3.252000e-12,4.437000e-16,1.668000e-11,3.115000e-12,0.000002,1.013000e-08
2,0.000038,1.393000e-14,0.000003,2.261000e-09,6.842000e-13,1.026000e-22,8.832000e-24,4.603000e-10,2.113000e-08,2.244000e-13,...,0.000086,0.000027,5.011000e-15,0.000344,4.015000e-12,4.892000e-16,1.776000e-11,3.119000e-12,0.000002,1.013000e-08
3,0.000038,1.741000e-14,0.000004,2.261000e-09,6.758000e-13,1.177000e-22,8.410000e-24,4.582000e-10,2.098000e-08,2.244000e-13,...,0.000086,0.000027,6.869000e-15,0.000328,4.957000e-12,5.443000e-16,1.901000e-11,3.124000e-12,0.000002,1.013000e-08
4,0.000038,2.565000e-14,0.000005,2.261000e-09,6.581000e-13,1.437000e-22,7.567000e-24,4.539000e-10,2.066000e-08,2.244000e-13,...,0.000086,0.000027,1.187000e-14,0.000297,7.044000e-12,6.634000e-16,2.150000e-11,3.134000e-12,0.000002,1.013000e-08

In [6]:
db.to_csv(rdrive + 'nuc32.act', sep = ' ', header=False)

In [ ]:
minidb = db.sample(150)
minidb.reset_index(drop=True, inplace=True)
minidb

In [ ]:
#minidb.to_csv('test2row.act', sep = ' ', header=False)
minidb.to_csv('test150row.act', sep = ' ', header=False)

In [ ]:
with open('NucNameList.txt', 'w') as f:
    for nuc in nuc_list:
        gadnuc = nuc[0].upper() + nuc[1:]
        f.write(gadnuc + '\n')

In [7]:
#test